### ISSUE TITLE
Rich presence in discord continues counting down the time if you are paused

### ISSUE THREAD

**Issue by Johnny0403** [FizzyApple12/BeatSaberPresence#1]
Basically what the title says, it's not a huge issue but something I thought I should bring up. I'm using an oculus quest 1 on steam with -vrmode oculus if that matters. Default config and everything with version 2.0.0. Once the timer in discord hits 0:00 it just stays at 0:00 until I exit back to the main menu.

**Comment by FizzyApple12** [comment]
Oops, I forgot to account for pausing, sorry about that. I can fix that for the release of either 2.1.0 or 2.1.1 depending on the release cycle of another library.
