### ISSUE TITLE
Mod doesnt appear on ingame mod options

### ISSUE THREAD

**Issue by Acorde17** [FizzyApple12/BeatSaberPresence#15]
The .dll is installed on .../Plugins but it doesn't appear in-game and the mod itself doesn't work.

I'm using version 25.0 and I've modded my bsaber with ModAsisstant.

**Comment by Acorde17** [comment]
Ok, I'm very stupid, sorry.

**Comment by CodyMarkix** [comment]
what the hell did you do to fix it
