### ISSUE TITLE
Breaking if user doesn't have Discord open

### ISSUE THREAD

**Issue by Zingabopp** [FizzyApple12/BeatSaberPresence#5]
When Discord isn't open, `DiscordCore.DiscordClient.GetUserManager()` return null, which is throwing a NullReferenceException in `PresenceController.Initialize()`. This is called by Zenject which may be breaking other things that use Zenject. You'll have to adjust and thoroughly test the case where someone doesn't have Discord open when the game is launched. Probably would be best to condition adding your installers on a non-null UserManager (but also test and handle Discord being closed while the game is running).

**Comment by FizzyApple12** [comment]
Just released v3.0.2 which should fix this issue.
